language: cpp

services:
  - docker

sudo: required
dist: trusty
osx_image: xcode10.1

env:
  global:
    - QPMX_CACHE_DIR=$HOME/.qpmx-cache
    - QT_VER=5.12.1
    - DOCKER_IMAGE=base
    - MAKE_RUN_TESTS=true

matrix:
  include:
    - os: linux
      env:
        - PLATFORM=gcc_64
    - os: linux
      env:
        - PLATFORM=android_arm64_v8a
    - os: linux
      env:
        - PLATFORM=android_armv7
    - os: linux
      env:
        - PLATFORM=android_x86
    - os: osx
      env:
        - PLATFORM=clang_64
    - os: osx
      env:
        - PLATFORM=ios

before_install:
  - git clone https://github.com/Skycoder42/QtModules.git ./qtmodules-travis
  - travis_wait 40 ./qtmodules-travis/ci/$TRAVIS_OS_NAME/setup.sh

script:
  - ./tests/setup-travis.sh
  - ./qtmodules-travis/ci/$TRAVIS_OS_NAME/build.sh

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
