image:
  - Visual Studio 2017
  - Visual Studio 2015

version: build-{build}

environment:
  QT_VER: 5.12.1
  MAKE_RUN_TESTS: true

  matrix:
    - PLATFORM: msvc2017_64
    - PLATFORM: mingw73_64
    - PLATFORM: winrt_x64_msvc2017
    - PLATFORM: msvc2017
    - PLATFORM: winrt_x86_msvc2017
    - PLATFORM: winrt_armv7_msvc2017
    - PLATFORM: msvc2015_64

matrix:
  exclude:
    - PLATFORM: msvc2017_64
      image: Visual Studio 2015
    - PLATFORM: mingw73_64
      image: Visual Studio 2015
    - PLATFORM: winrt_x64_msvc2017
      image: Visual Studio 2015
    - PLATFORM: msvc2017
      image: Visual Studio 2015
    - PLATFORM: winrt_x86_msvc2017
      image: Visual Studio 2015
    - PLATFORM: winrt_armv7_msvc2017
      image: Visual Studio 2015
    - PLATFORM: msvc2015_64
      image: Visual Studio 2017

install:
  - git clone https://github.com/Skycoder42/QtModules.git .\qtmodules-travis
  - .\qtmodules-travis\ci\win\setup.bat

build_script:
  - .\tests\setup-appveyor.bat
  - .\qtmodules-travis\ci\win\build.bat
