image:
  - Visual Studio 2019

version: build-{build}

environment:
  QT_VER: 5.14.1
  MAKE_RUN_TESTS: true
  TARGET_NAME: qdep

  matrix:
    - PLATFORM: msvc2019_64
    - PLATFORM: mingw73_64
    - PLATFORM: winrt_x64_msvc2019
    - PLATFORM: msvc2019
    - PLATFORM: mingw73_32
    - PLATFORM: winrt_x86_msvc2019
    - PLATFORM: winrt_armv7_msvc2019

install:
  - git clone https://github.com/Light-Wizzard/QtModules.git .\qtmodules-travis
  - .\qtmodules-travis\ci\win\setup.bat

build_script:
  - .\tests\setup-appveyor.bat
  - .\qtmodules-travis\ci\win\build.bat
